### ISSUE TITLE
Setup initial npm project

### ISSUE THREAD

**Issue by frankwiles** [simplworld/simpl-chat#1]
Need to be able to install this via github with `npm install https://github.com/simplworld/simpl-chat/`.

**Comment by mightym** [comment]
The requirement to theme/control the visual appearance implies a few options that have advantages and disadvantages:

1. Ship a component without any styling. Quite common eg https://react-slick.neostack.com It provides the styles for the core functionality. But everything else can be applied by you preferred way (CSS Classes, CSS Modules, Inline Styles etc)
2. Ship a component with base styles in CSS (precompiled in the repo) which you than can override with your own CSS 
3. Ship a component that has its own base styles. Which can be modified via properties (thats similar what we had on Wharton Interactive) 

My personal experience is that 1 & 3 are the best from a developer standpoint. At 2. you always have to include the CSS of the  component in addition in your project. 

But maybe you also have some preferences there?
